CREATE DATABASE IF NOT EXISTS car_rental;
USE car_rental;

-- Tabela: klienci
CREATE TABLE klienci (
    ID_KLIENT INT NOT NULL AUTO_INCREMENT,
    IMIE TEXT NOT NULL,
    NAZWISKO TEXT NOT NULL,
    MIEJSCOWOSC TEXT NOT NULL,
    ULICA TEXT NOT NULL,
    NR_DOMU CHAR(5) NOT NULL,
    KOD_POCZT CHAR(6) NOT NULL,
    NR_TEL TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    NR_PRAWAJAZDY CHAR(11) NOT NULL,
    DATA_WAZNOSCI_PJ DATE NOT NULL,
    NR_KONTA CHAR(26) NOT NULL,
    NR_KARTY CHAR(16) NOT NULL,
    PRIMARY KEY (ID_KLIENT)
) ENGINE = InnoDB;

-- Tabela: samochody
CREATE TABLE samochody (
    ID_SAMOCHOD INT NOT NULL AUTO_INCREMENT,
    MARKA TEXT NOT NULL,
    MODEL TEXT NOT NULL,
    NR_REJ VARCHAR(10) NOT NULL,
    NR_DOWODU_REJ VARCHAR(17) NOT NULL,
    VIN VARCHAR(17) NOT NULL,
    ROK_PROD YEAR NOT NULL,
    TYP_PALIWA ENUM('BENZYNA','DIESEL','ELEKTRYCZNY','HYBRYDA','INNE') NOT NULL,
    PRZEBIEG INT NOT NULL,
    DATA_PRZEGL DATE NOT NULL,
    DATA_KOL_PRZEGL DATE NOT NULL,
    NAPED ENUM('FWD','RWD','AWD','4X4','INNE') NOT NULL,
    CENA SMALLINT NOT NULL,
    TYP_NADWOZIA ENUM('COUPE','KABRIOLET','KOMBI','KOMPAKT','MINIVAN','SEDAN','VAN','SUV','INNE') NOT NULL,
    KLASA ENUM('ECO','STANDARD','PREMIUM','LUXURY','SPORT') NOT NULL,
    ILOSC_MIEJSC SMALLINT NOT NULL,
    POJE_BAGAZNIKA SMALLINT NOT NULL,
    PRIMARY KEY (ID_SAMOCHOD)
) ENGINE = InnoDB;

-- Tabela: serwis
CREATE TABLE serwis (
    ID_SERWIS INT NOT NULL AUTO_INCREMENT,
    ID_SAMOCHOD INT NOT NULL,
    RODZAJ_SERWIS TEXT NOT NULL,
    DATA_SERWIS DATE NOT NULL,
    KOSZT_SERWIS MEDIUMINT NOT NULL,
    WYKONAWCA TEXT NOT NULL,
    OPIS_SERWIS TEXT NOT NULL,
    PRIMARY KEY (ID_SERWIS),
    FOREIGN KEY (ID_SAMOCHOD) REFERENCES samochody(ID_SAMOCHOD)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabela: ubezpieczenia
CREATE TABLE ubezpieczenia (
    ID_UBEZPIECZENIA INT NOT NULL AUTO_INCREMENT,
    ID_SAMOCHOD INT NOT NULL,
    NUMER_POLISY TEXT NOT NULL,
    RODZAJ_UBEZP ENUM('OC','AC') NOT NULL,
    DATA_ROZPOCZ DATE NOT NULL,
    DATA_ZAKONCZ DATE NOT NULL,
    FIRMA_UBEZP TEXT NOT NULL,
    KOSZT_UBEZP SMALLINT NOT NULL,
    UWAGI TEXT NOT NULL,
    PRIMARY KEY (ID_UBEZPIECZENIA),
    FOREIGN KEY (ID_SAMOCHOD) REFERENCES samochody(ID_SAMOCHOD)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabela: wyposazenie
CREATE TABLE wyposazenie (
    ID_SAMOCHOD INT NOT NULL,
    KLIMATYZACJA BOOLEAN NOT NULL,
    EKRAN_DOTYK BOOLEAN NOT NULL,
    RADIO BOOLEAN NOT NULL,
    GPS BOOLEAN NOT NULL,
    BLUETOOTH BOOLEAN NOT NULL,
    ANDROID_AUTO BOOLEAN NOT NULL,
    APPLE_CARPLAY BOOLEAN NOT NULL,
    PODGRZ_FOTELI BOOLEAN NOT NULL,
    PODGRZ_KIEROWNICY BOOLEAN NOT NULL,
    ELEKTR_SZYBY BOOLEAN NOT NULL,
    ELEKTR_LUST BOOLEAN NOT NULL,
    TEMPOMAT BOOLEAN NOT NULL,
    KAMERA_COFANIA BOOLEAN NOT NULL,
    HAK BOOLEAN NOT NULL,
    DACH_PANORAM BOOLEAN NOT NULL,
    ABS BOOLEAN NOT NULL,
    ESP BOOLEAN NOT NULL,
    ASR BOOLEAN NOT NULL,
    FCW BOOLEAN NOT NULL,
    AEB BOOLEAN NOT NULL,
    LKA BOOLEAN NOT NULL,
    SYS_ROZP_ZNAK BOOLEAN NOT NULL,
    BSM BOOLEAN NOT NULL,
    CZUJNIKI_PARK BOOLEAN NOT NULL,
    KAMERY_360 BOOLEAN NOT NULL,
    PRIMARY KEY (ID_SAMOCHOD),
    FOREIGN KEY (ID_SAMOCHOD) REFERENCES samochody(ID_SAMOCHOD)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabela: reklamacje
CREATE TABLE reklamacje (
    ID_REKLAMACJI INT NOT NULL AUTO_INCREMENT,
    ID_KLIENT INT NOT NULL,
    ID_SAMOCHOD INT NOT NULL,
    DATA_ZGLOSZ DATE NOT NULL,
    STATUS ENUM('przyjeto','odrzucono','w_rozpatrzeniu') NOT NULL,
    DATA_ROZPATRZ DATE NOT NULL,
    POWOD_REKLAM TEXT NOT NULL,
    PRIMARY KEY (ID_REKLAMACJI),
    FOREIGN KEY (ID_KLIENT) REFERENCES klienci(ID_KLIENT)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_SAMOCHOD) REFERENCES samochody(ID_SAMOCHOD)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabela: incydenty
CREATE TABLE incydenty (
    ID_INCYDENT INT NOT NULL AUTO_INCREMENT,
    ID_KLIENT INT NOT NULL,
    ID_SAMOCHOD INT NOT NULL,
    DATA_ZGLOSZ DATE NOT NULL,
    DATA_ROZWIAZ DATE NOT NULL,
    OPIS TEXT NOT NULL,
    STATUS TEXT NOT NULL,
    UWAGI_ROZWIAZ TEXT NOT NULL,
    PRIMARY KEY (ID_INCYDENT),
    FOREIGN KEY (ID_KLIENT) REFERENCES klienci(ID_KLIENT)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_SAMOCHOD) REFERENCES samochody(ID_SAMOCHOD)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabela: umowy
CREATE TABLE umowy (
    NUMER_UMOWY INT NOT NULL AUTO_INCREMENT,
    ID_KLIENT INT NOT NULL,
    ID_SAMOCHOD INT NOT NULL,
    DATA_WYPOZYCZ DATE NOT NULL,
    DATA_ZWR_PLAN DATE NOT NULL,
    DATA_ZWR_RZECZ DATE NOT NULL,
    KOSZT_WYNAJMU SMALLINT NOT NULL,
    STATUS_PLATNOSCI BOOLEAN NOT NULL,
    UWAGI_KLIENTA TEXT NOT NULL,
    ID_REKLAMACJI INT,
    ID_INCYDENT INT,
    KARA MEDIUMINT NOT NULL,
    POZIOM_ZBIORNIK ENUM('1','3/4','1/2','1/4') NOT NULL,
    PRIMARY KEY (NUMER_UMOWY),
    FOREIGN KEY (ID_KLIENT) REFERENCES klienci(ID_KLIENT)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_SAMOCHOD) REFERENCES samochody(ID_SAMOCHOD)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_REKLAMACJI) REFERENCES reklamacje(ID_REKLAMACJI)
        ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (ID_INCYDENT) REFERENCES incydenty(ID_INCYDENT)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabela: platonosci 
CREATE TABLE platonosci (
    ID_PLATNOSCI INT NOT NULL AUTO_INCREMENT,
    NUMER_UMOWY INT NOT NULL,
    DATA_PLATNOSCI DATE NOT NULL,
    METODA_PLATNOS ENUM('przelew','karta','gotowka','czek') NOT NULL,
    KWOTA_PLATNOSCI INT NOT NULL,
    STATUS_PLATNOSCI BOOLEAN NOT NULL,
    PRIMARY KEY (ID_PLATNOSCI),
    FOREIGN KEY (NUMER_UMOWY) REFERENCES umowy(NUMER_UMOWY)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabela: oddzialy
CREATE TABLE oddzialy (
    ID_ODDZIAL INT NOT NULL AUTO_INCREMENT,
    NAZWA_ODDZIAL TEXT NOT NULL,
    ADRES TEXT NOT NULL,
    NR_TEL TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    KIEROWNIK TEXT NOT NULL,
    LICZBA_PRACOW SMALLINT NOT NULL,
    KRAJ TEXT NOT NULL,
    PRIMARY KEY (ID_ODDZIAL)
) ENGINE = InnoDB;

-- Tabela: pracownicy
CREATE TABLE pracownicy (
    ID_PRACOWNIK INT NOT NULL AUTO_INCREMENT,
    IMIE TEXT NOT NULL,
    NAZWISKO TEXT NOT NULL,
    STANOWISKO TEXT NOT NULL,
    NR_TEL TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    NAZWA_ODDZIALU TEXT NOT NULL,
    RODZAJ_UMOWY TEXT NOT NULL,
    DATA_ZATRUDNIENIA DATE NOT NULL,
    NR_DOWODU_OSOB CHAR(6) NOT NULL,
    SYSTEM_LOGIN TEXT NOT NULL,
    SYSTEM_HASLO TEXT NOT NULL,
    WYNAGRODZENIE MEDIUMINT NOT NULL,
    PRIMARY KEY (ID_PRACOWNIK)
) ENGINE = InnoDB;
